version: '3.4'

services:
  mywebapi:
    image: mywebapi:dev
    container_name: MyWebAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MyWebAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_mywebapi$
    volumes:
      - C:\Users\narov\source\repos\WebFrontEnd\MyWebAPI:/app
      - C:\Users\narov\source\repos\WebFrontEnd:/src
      - C:\Users\narov\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_mywebapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_mywebapi$ \"/app/bin/Debug/netcoreapp3.1/MyWebAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  webfrontend:
    image: webfrontend:dev
    container_name: WebFrontEnd
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebFrontEnd"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webfrontend$
    volumes:
      - C:\Users\narov\source\repos\WebFrontEnd\WebFrontEnd:/app
      - C:\Users\narov\source\repos\WebFrontEnd:/src
      - C:\Users\narov\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webfrontend$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webfrontend$ \"/app/bin/Debug/netcoreapp3.1/WebFrontEnd.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
